### ISSUE TITLE
"Performance Hints" blog post not found.

### ISSUE THREAD

**Issue by ghost** [drolbr/overpass-blog#2]
The following is a dead link: https://dev.overpass-api.de/blog/performance_hints.html

And it is linked to from the blog: https://dev.overpass-api.de/blog/

**Comment by drolbr** [comment]
The blog post "performance hints" gives unhelpful advice, at least partially. For that reason I intended to not have it in the index. However, not having it in this repo is confusing, thus I have added it right now.
