### ISSUE TITLE
Blog code errors

### ISSUE THREAD

**Issue by DaveF63** [drolbr/overpass-blog#3]
Hi
I'm finding Overpass's blog very useful, but frustrated that many code example throw an error in OP Turbo. Would it be possible to check & update them please?

Examples:
name = set(t[name]), requires quotation marks around 'name'
(._; .result)->.result; requires a semi-colon after the first 'result'

**Comment by drolbr** [comment]
Thank you very much. I hope I have caught all the syntax bugs with the commit 2f8dd842177771c9e59e45c5bb753c496e0d087c
